---
- name: clone repository
  git:
    repo: "{{ index_repository }}"
    dest: "{{ index_root }}"
    accept_hostkey: yes
  tags: clone

- name: set configuration files
  template:
    src: index.j2
    dest: /etc/nginx/sites-available/index
    owner: root
    group: root
    mode: 0644
  notify: reload nginx
  tags: configuration

- name: get letsencrypt certification
  command: letsencrypt certonly --webroot -d {{ index_hostname }} -w {{ index_root }} --email {{ notification_email }} --agree-tos --keep-until-expiring --non-interactive

- name: enable configuration files
  file:
    state: link
    src: /etc/nginx/sites-available/index
    dest: /etc/nginx/sites-enabled/index
    owner: root
    group: root
  notify: reload nginx
  tags: configuration

- name: start nginx
  service: name=nginx state=started enabled=yes
