---
- name: set configuration files
  template:
    src: "{{ item.src }}"
    dest: "/etc/nginx/sites-available/{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - src: http.j2
      dest: http
    - src: https.j2
      dest: https
  tags: configuration

- name: set certificate file
  copy:
    src: "{{ ssl_certificate }}"
    dest: "/etc/ssl/certs/{{ ssl_certificate }}"
    owner: root
    group: root
    mode: 0644
  tags: configuration

- name: set certificate key file
  copy:
    src: "{{ ssl_certificate_key }}"
    dest: "/etc/ssl/private/{{ ssl_certificate_key }}"
    owner: root
    group: root
    mode: 0400
  tags: configuration

- name: enable configuration files
  file:
    state: link
    src: "/etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    owner: root
    group: root
  with_items:
    - http
    - https
  notify: reload nginx
  tags: configuration

- name: start nginx
  service: name=nginx state=started enabled=yes
