---
- name: clone repository
  git:
    repo: "{{ index_repository }}"
    dest: "{{ index_root }}"
    accept_hostkey: yes
  tags: clone

- name: set configuration files
  template:
    src: index.j2
    dest: /etc/nginx/sites-available/index
    owner: root
    group: root
    mode: 0644
  notify: reload nginx
  tags: configuration

- name: set certificate file
  copy:
    src: "{{ item.src }}"
    dest: /etc/ssl/{{ item.dest }}
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - src: "{{ ssl_certificate }}"
      dest: certs/{{ ssl_certificate }}
      mode: 0644
    - src: "{{ ssl_certificate_key }}"
      dest: private/{{ ssl_certificate_key }}
      mode: 0400
  notify: reload nginx
  tags: configuration

- name: enable configuration files
  file:
    state: link
    src: /etc/nginx/sites-available/index
    dest: /etc/nginx/sites-enabled/index
    owner: root
    group: root
  notify: reload nginx
  tags: configuration

- name: start nginx
  service: name=nginx state=started enabled=yes
