---
- name: restart nginx
  service: name=nginx state=restarted

- name: test nginx
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: False

- name: reload nginx
  service: name=nginx state=reloaded
