---
- name: add certbot apt repository
  apt_repository:
    repo: 'ppa:certbot/certbot'
  tags: package

- name: install certbot
  apt: name=python-certbot-nginx state=present update_cache=yes
  tags: package

- name: auto update certification
  cron:
    name: letsencrypt
    cron_file: letsencrypt
    user: root
    special_time: daily
    job: sh -c '/usr/bin/certbot renew && /usr/sbin/service nginx reload' >> {{ letsencrypt_log }} 2>&1
